ProjectAspNETv2/Controllers/ProprietaireController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ProjectAspNETv2.Models;

namespace ProjectAspNETv2.Controllers
{
    [Authorize(Roles ="Marchand")]
    public class ProprietaireController : Controller
    {
        private Entities1 db = new Entities1();


        [HttpGet]
        public ActionResult Index()
        {

            // get l'utlisateur auth
            var id = User.Identity.GetUserId();
            var prop = db.Proprietaires.Single(p => p.UserId == id);
           
            int propID = prop.Id;

            // get les produit de l'utilisateur auth
            var data = db.Produits.Where(p => p.propreitaireId == propID).ToList();
            
            var data2 = new List<Produit>();  // les produits ajoutes ce mois
            var data3 = new List<Produit>();  // les 3 produits ajoutes recement
            var ProductsToday = new List<Produit>(); // les produits de ce jour
            var ProductsWeek = new List<Produit>();
            //var vues = new List<int>();

            List<int> vues = new List<int>();    // liste des vues des produits
            var TopProducts = new List<Produit>();  // top product basee sur les vues


            foreach (Produit p in data)
            {
                TimeSpan dif = (TimeSpan)(DateTime.Now - p.createdAt);

                double jr = dif.TotalDays;

                if (jr <= 30)
                {
                    data2.Add(p);
                }

                if (jr <= 7)
                {
                    ProductsWeek.Add(p);
                }

                if (jr <= 1)
                {
                    ProductsToday.Add(p);
                }

                vues.Add(p.Vues.Count);

            }
            if(data.Count() >= 3)
            {
                data3 = db.Produits.OrderByDescending(i => i.createdAt).Take(3).ToList();
                TopProducts = data.OrderByDescending(i => i.Vues.Count).Take(3).ToList();
            }
            else
            {
                data3 = db.Produits.OrderByDescending(i => i.createdAt).Take(data.Count()).ToList();
                TopProducts = data.OrderByDescending(i => i.Vues.Count).Take(data.Count()).ToList();
            }

            var VuesToday = db.Vues.Where(v => v.Produit.propreitaireId == propID && ((DateTime)v.created_at).Day == DateTime.Now.Day).ToList().Count();
            var VuesMois = db.Vues.Where(v => v.Produit.propreitaireId == propID && ((DateTime)v.created_at).Month == DateTime.Now.Month).ToList().Count();

            
            ViewBag.VuesToday = VuesToday;
            ViewBag.VuesMois = VuesMois;
            ViewBag.AllProducts = data;
            ViewBag.ProdMois = data2.Count();
            ViewBag.TotalProducts = data.Count();
            ViewBag.RecentProducts = data3;
            ViewBag.TopProducts = TopProducts;
            ViewBag.prp = db.Proprietaires.Count();
            ViewBag.produits = db.Produits.Count();
            ViewBag.ProductsToday = ProductsToday;
            ViewBag.ProductsWeek = ProductsWeek;
            

            return View("Home");

        }


        [HttpGet]
        public ActionResult GetAllProducts()
        {
            var id = User.Identity.GetUserId();
            var prop = db.Proprietaires.Single(p => p.UserId == id);

            int propID = prop.Id;
            return Redirect(Url.Action("Index", "Produits",new { id = propID }));
            
        }



        [HttpGet]
        public ActionResult GetProductsNoConfirmed()
        {
            var id = User.Identity.GetUserId();
            var prop = db.Proprietaires.Single(p => p.UserId == id);

            int propID = prop.Id;

            var data = db.Produits.Where(p => p.propreitaireId == propID && (p.status == "1"  || p.status == "3")).ToList();

                ViewBag.MyList = data;
                return View("ProductsRef");
            
        }






        [HttpGet]
        public ActionResult GetStatistics()
        {
            return View("Statistic");
        }






        public ActionResult MyChart()
        {
            var id = User.Identity.GetUserId();
            var prop = db.Proprietaires.Single(p2 => p2.UserId == id);

            int propID = prop.Id;

            DateTime dateAuj0 = DateTime.Now;
            DateTime dateAuj1 = dateAuj0.AddDays(-1);
            DateTime dateAuj2 = dateAuj0.AddDays(-2);
            DateTime dateAuj3 = dateAuj0.AddDays(-3);
            DateTime dateAuj4 = dateAuj0.AddDays(-4);
            DateTime dateAuj5 = dateAuj0.AddDays(-5);
            DateTime dateAuj6 = dateAuj0.AddDays(-6);

            var Dates = new List<DateTime>();
            Dates.Add(dateAuj0);
            Dates.Add(dateAuj1);
            Dates.Add(dateAuj2);
            Dates.Add(dateAuj3);
            Dates.Add(dateAuj4);
            Dates.Add(dateAuj5);
            Dates.Add(dateAuj6);

            var data = new List<Vue>();

            // initialiser les vues 
            var vues2 = new List<int>();
            
            int p = 0;


            foreach (DateTime dt in Dates)
            {
              p =  db.Vues.Where(v => ((DateTime)v.created_at).Day == dt.Day  && v.Produit.propreitaireId == propID).Count();
                vues2.Add(p);

            }
           

            string[] xv = { dateAuj6.ToString("dd/MM"), dateAuj5.ToString("dd/MM"), dateAuj4.ToString("dd/MM"), dateAuj3.ToString("dd/MM"), dateAuj2.ToString("dd/MM"), dateAuj1.ToString("dd/MM"), dateAuj0.ToString("dd/MM") };
            int[] yv = { vues2[6], vues2[5], vues2[4], vues2[3], vues2[2], vues2[1], vues2[0] };

            new System.Web.Helpers.Chart(width: 800, height: 200)
                .AddTitle("Les vues dans les 7 derniers jours")
                .AddSeries(
                   chartType: "Column",
                   xValue: xv,
                   xField:"Les vues",
                   yValues: yv,
                   yFields:"Les jours"
                ).Write("png");

            return null;



        }


        public ActionResult MyChart2()
        {
            var id = User.Identity.GetUserId();
            var prop = db.Proprietaires.Single(p => p.UserId == id);

            int propID = prop.Id;

            // initialiser les vues 

            var vues = db.Vues.ToList();
            var vues2 = new List<int>();
            var cats = db.Categories.ToList();

            



            foreach (Category cat in cats)
            {
                int s = 0;
                foreach (Produit pr in cat.Produits)
                {
                     if(pr.propreitaireId == propID)
                     {
                         s = s + pr.Vues.Count;
                     }

                }
                vues2.Add(s);

            }


            List<string> xv = new List<string>();
            List<int> yv = new List<int>();

            foreach(Category cat in cats)
            {
                xv.Add(cat.Name);
            
            }
            foreach (int vu in vues2)
            {
                yv.Add(vu);
            }



            new System.Web.Helpers.Chart(width: 800, height: 200)
                .AddTitle("Total des vues selon les categories")
                .AddSeries(
                   chartType: "Column",
                   xValue: xv,
                   xField: "Les vues",
                   yValues: yv,
                   yFields: "Les jours"
                ).Write("png");

            return null;



        }





        [HttpGet]
        public ActionResult GetHistorique()
        {
            var id2 = User.Identity.GetUserId();
            var prop = db.Proprietaires.Single(p => p.UserId == id2);
            int propID = prop.Id;
      
                var data = db.Historiques.Where(h => h.proprietaireId == propID).ToList();


                ViewBag.Operations = data;
              

                return View("Historique");
            

        }



        [HttpPost]

        public ActionResult DeleteOperation(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.BadRequest);
            }
            Historique h = db.Historiques.Find(id);

            db.Historiques.Remove(h);
            db.SaveChanges();

            return Redirect(Url.Action("GetHistorique", "Proprietaire"));
        }



        [HttpGet]
        public ActionResult Support()
        {
            return View("Support");
        }

        [HttpPost]

        public ActionResult SendMessageToSupport(string email, string subject, string message)
        {
            var id = User.Identity.GetUserId();
            var prop = db.Proprietaires.Single(p => p.UserId == id);
            int propID = prop.Id;


            ContactSupport cs = new ContactSupport();
            cs.Email = email;
            cs.subject = subject;
            cs.message = message;
            cs.marchandId = propID;
            int ids = db.ContactSupports.Count(); ids++;
            cs.Id = ids;
            if (ModelState.IsValid)
            {
                db.ContactSupports.Add(cs);
                db.SaveChanges();

            }
            return Redirect(Url.Action("Support", "Proprietaire"));
        }

        public ActionResult Profile()
        {
            var idu = User.Identity.GetUserId();
            var prop = db.Proprietaires.Where(p => p.UserId == idu).FirstOrDefault();
            return View(prop);
        }
    }
}

ProjectAspNETv2/Controllers/ProprietairesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectAspNETv2.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Configuration;

namespace ProjectAspNETv2.Controllers
{
    public class ProprietairesController : Controller
    {
        private Entities1 db = new Entities1();
        

        // GET: Proprietaires
        public async Task<ActionResult> Index()
        {
            
            var proprietaires = db.Proprietaires.Include(p => p.AspNetUser);
            return View(await proprietaires.ToListAsync());
        }

        // GET: Proprietaires/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proprietaire proprietaire = await db.Proprietaires.FindAsync(id);
            if (proprietaire == null)
            {
                return HttpNotFound();
            }
            return View(proprietaire);
        }

        // GET: Proprietaires/Create
        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            return View();
        }

        // POST: Proprietaires/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,isCompany,Logo,Tel,Adresse,Ville")] Proprietaire proprietaire, HttpPostedFileBase Logo)
        {

            if (ModelState.IsValid)
            {
                

                try
                {
                    if (Logo != null && Logo.ContentLength > 0)
                    {


                        string extension = Path.GetExtension(Logo.FileName);
                        var filename = DateTime.Now.ToString("yymmssfff") + extension;
                        var savePath = Path.Combine(Server.MapPath("~/propimages/Logos"), filename);

                        Logo.SaveAs(savePath);
                        proprietaire.Logo = "/propimages/Logos/" + filename;
                        proprietaire.isHonored = false;
                        ViewBag.FileStatus = "File uploaded successfully.";
                    } else
                    {
                        ViewBag.FileStatus = "Error while file uploading.";
                        ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", proprietaire.UserId);
                        return View(proprietaire);
                    }

                }
                catch (Exception e)
                {
                    ViewBag.FileStatus = "Error while file uploading.";
                }

                /**/
                proprietaire.UserId = User.Identity.GetUserId();
                proprietaire.isBlocked = false;
                proprietaire.created_at = DateTime.Now;
                proprietaire.isHonored = false;
                db.Proprietaires.Add(proprietaire);

                var userManager = new UserManager<ApplicationUser, string>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                //await userManager.AddToRole(User.Identity.GetUserId(), "Marchand");

                await db.SaveChangesAsync();
                ModelState.Clear();
                return RedirectToAction("Index","Welcome");

            }

            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", proprietaire.UserId);
            return View(proprietaire);
        }

        // GET: Proprietaires/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proprietaire proprietaire = await db.Proprietaires.FindAsync(id);
            if (proprietaire == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", proprietaire.UserId);
            return View(proprietaire);
        }

        // POST: Proprietaires/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,UserId,isCompany,Tel,Adresse,Ville,Logo,isHonored,isBlocked")] Proprietaire proprietaire)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proprietaire).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email", proprietaire.UserId);
            return View(proprietaire);
        }

        // GET: Proprietaires/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proprietaire proprietaire = await db.Proprietaires.FindAsync(id);
            if (proprietaire == null)
            {
                return HttpNotFound();
            }
            return View(proprietaire);
        }

        // POST: Proprietaires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Proprietaire proprietaire = await db.Proprietaires.FindAsync(id);


            foreach(Produit pp in proprietaire.Produits)
            {
               pp.Images.ToList().Clear();
               pp.Historiques.ToList().Clear();
               pp.Vues.ToList().Clear();
                db.SaveChanges();

                db.Produits.Remove(pp);

                db.SaveChanges();
            }

            proprietaire.ContactSupports.ToList().Clear();
            

            
            db.Proprietaires.Remove(proprietaire);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectAspNETv2/Views/Proprietaires/Create.cshtml
@model ProjectAspNETv2.Models.Proprietaire

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutWelcomePage.cshtml";

}














<!--====== App Content ======-->
<div class="app-content">

    <!--====== Section 1 ======-->
    <div class="u-s-p-y-60">

        <!--====== Section Content ======-->
        <div class="section__content">
            <div class="container">
                <div class="breadcrumb">
                    <div class="breadcrumb__wrap">
                        <ul class="breadcrumb__list">
                            <li class="has-separator">

                                <a href="index.html">Home</a>
                            </li>
                            <li class="has-separator">

                                <a href="signup.html">Signup</a>
                            </li>
                            <li class="is-marked">

                                <a href="signup.html">Marchand</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--====== End - Section 1 ======-->
    <!--====== Section 2 ======-->
    <div class="u-s-p-b-60">

        <!--====== Section Intro ======-->
        <div class="section__intro u-s-m-b-60">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section__text-wrap">
                            <h1 class="section__heading u-c-secondary">FINALISATION DU COMPTE</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--====== End - Section Intro ======-->
        <!--====== Section Content ======-->
        <div class="section__content">
            <div class="container">
                <div class="row row--center">
                    <div class="col-lg-6 col-md-8 u-s-m-b-30">
                        <div class="l-f-o">
                            <div class="l-f-o__pad-box">
                                <h1 class="gl-h1">INFORMATION DU MARCHAND</h1>
                                @using (Html.BeginForm("Create", "Proprietaires", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.ValidationSummary("", new { @class = "text-danger" })

                                    <div class="u-s-m-b-15">
                                        <div class="u-s-m-b-15">
                                            @Html.Label("S'inscrire en tant que", new { @class = "gl-label" })
                                        </div>
                                        <div class="radio-box newsletter__radio">
                                            @Html.RadioButtonFor(model => model.isCompany, "false")

                                            <div class="radio-box__state radio-box__state--primary">
                                                @Html.Label("Particulier", new { @class = "radio-box__label", @style = "color : #333" })
                                            </div>
                                        </div>
                                        <div class="radio-box newsletter__radio">
                                            @Html.RadioButtonFor(model => model.isCompany, "true")

                                            <div class="radio-box__state radio-box__state--primary">
                                                @Html.Label("Entreprise", new { @class = "radio-box__label", @style = "color : #333;" })

                                            </div>
                                        </div>
                                        @Html.ValidationMessageFor(model => model.isCompany, "", new { @class = "text-danger" })

                                    </div>

                                    <div class="u-s-m-b-30">
                                        @Html.Label("Full Name", new { @class = "gl-label" })
                                        @Html.TextBoxFor(model => model.Name, new { @class = "input-text input-text--primary-style", placeholder = "Your Name" })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

                                    </div>
                                    <div class="u-s-m-b-30">
                                        @Html.LabelFor(model => model.Tel, new { @class = "gl-label" })
                                        @Html.TextBoxFor(model => model.Tel, new { @class = "input-text input-text--primary-style", placeholder = "+212687120381" })
                                        @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })

                                    </div>
                                    <div class="u-s-m-b-30">

                                        @Html.LabelFor(model => model.Adresse, new { @class = "gl-label" })
                                        @Html.TextBoxFor(model => model.Adresse, new { @class = "input-text input-text--primary-style", placeholder = "Adresse CIN" })
                                        @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })

                                    </div>
                                    <div class="u-s-m-b-30">

                                        @Html.LabelFor(model => model.Ville, new { @class = "gl-label" })
                                        @Html.TextBoxFor(model => model.Ville, new { @class = "input-text input-text--primary-style", placeholder = "exemple : Fes" })
                                        @Html.ValidationMessageFor(model => model.Ville, "", new { @class = "text-danger" })

                                    </div>
                                    <div class="u-s-m-b-30">

                                        @Html.LabelFor(model => model.Logo, new { @class = "gl-label" })
                                        @Html.TextBoxFor(model => model.Logo, new { @class = "input-text input-text--primary-style", @type = "file" })
                                        @Html.ValidationMessageFor(model => model.Logo, "", new { @class = "text-danger" })

                                    </div>
                                    <div class="u-s-m-b-15">

                                        <button class="btn btn--e-transparent-brand-b-2" type="submit">CREATE</button>
                                    </div>
                                    <div class="u-s-m-b-15">
                                        @ViewBag.FileStatus
                                    </div>

                                    <a class="gl-link" href="#">Return to Home</a>

                                }

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--====== End - Section Content ======-->
    </div>
    <!--====== End - Section 2 ======-->
</div>
<!--====== End - App Content ======-->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectAspNETv2/Views/Proprietaires/Delete.cshtml
@model ProjectAspNETv2.Models.Proprietaire

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Proprietaire</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ville)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ville)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isHonored)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isHonored)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isBlocked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isBlocked)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectAspNETv2/Views/Proprietaires/Details.cshtml
@model ProjectAspNETv2.Models.Proprietaire

@{
    ViewBag.Title = "Details";

    Layout = "~/Views/Shared/_LayoutPageDashboard2.cshtml";

}

<h2>Details</h2>

<div>
    <h4>Proprietaire</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isCompany)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isCompany)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ville)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ville)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Logo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isHonored)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isHonored)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isBlocked)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isBlocked)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectAspNETv2/Views/Proprietaires/Index.cshtml
@model IEnumerable<ProjectAspNETv2.Models.Proprietaire>

@{
    ViewBag.Title = "Index";

    Layout = "~/Views/Shared/_LayoutPageDashboard1.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isCompany)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Adresse)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ville)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Logo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isHonored)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.isBlocked)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AspNetUser.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isCompany)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adresse)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Ville)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Logo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isHonored)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isBlocked)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser.Email)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>