ProjectAspNETv2/Models/Promotion.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAspNETv2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Promotion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promotion()
        {
            this.Produits = new HashSet<Produit>();
        }
    
        public int Id { get; set; }

        [StringLength(256, ErrorMessage = "le nom de la promotion doit avoir au minimum 3 lettres", MinimumLength = 3)]
        [Display(Name = "Description")]
        [Required(ErrorMessage = "la description est obligatoire")]
        public string Name { get; set; }

        [Range(1, 99, ErrorMessage = "le prix doit etre entre 1 et 99 ")]
        [Required(ErrorMessage = "le pourcentage est obligatoire")]
        public Nullable<int> Pourcentage { get; set; }

        [Display(Name = "Date de fin de validite")]
        [Required(ErrorMessage = "cette date est obligatoire")]
        public Nullable<System.DateTime> Date_Validite { get; set; }
        public Nullable<System.DateTime> Date_Creation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Produit> Produits { get; set; }
    }
}

ProjectAspNETv2/Controllers/PromotionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectAspNETv2.Models;

namespace ProjectAspNETv2.Controllers
{
    public class PromotionsController : Controller
    {
        private Entities1 db = new Entities1();

        // GET: Promotions
        public ActionResult Index()
        {
            return View(db.Promotions.ToList());
        }

        // GET: Promotions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotion promotion = db.Promotions.Find(id);
            if (promotion == null)
            {
                return HttpNotFound();
            }
            return View(promotion);
        }

        // GET: Promotions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Promotions/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Pourcentage,Date_Validite")] Promotion promotion)
        {
            if (ModelState.IsValid)
            {
                promotion.Date_Creation = DateTime.Now;
                db.Promotions.Add(promotion);
                db.SaveChanges();
                return RedirectToAction("Index");


            }

            return View(promotion);
        }

        // GET: Promotions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotion promotion = db.Promotions.Find(id);
            if (promotion == null)
            {
                return HttpNotFound();
            }
            return View(promotion);
        }

        // POST: Promotions/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Pourcentage,Date_Validite,Date_Creation")] Promotion promotion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(promotion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(promotion);
        }

        // GET: Promotions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Promotion promotion = db.Promotions.Find(id);
            if (promotion == null)
            {
                return HttpNotFound();
            }
            return View(promotion);
        }

        // POST: Promotions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Promotion promotion = db.Promotions.Find(id);
            db.Promotions.Remove(promotion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectAspNETv2/Views/Promotions/Create.cshtml
@model ProjectAspNETv2.Models.Promotion

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPageDashboard2.cshtml";
}




<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Promotions</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->
<div class="main-body">
    <div class="page-wrapper">
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Nouvelle promotion</h5>
                    </div>
                    <div class="card-block table-border-style">

                        @using (Html.BeginForm("Create", "Promotions", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="form-group">

                                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Pourcentage, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Pourcentage, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Pourcentage, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Date_Validite, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Date_Validite, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Date_Validite, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Create" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div class="row mt-5" style="justify-content : end;">
                            <div style="width : fit-content;">
                                <div style="display:inline-block;">
                                    <button class="btn btn-primary" type="button">
                                        <a href="@Url.Action("Index" , "Promotions" )" style="display: inline-block; color : #fff ; text-decoration : none;">Liste</a>

                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ Main Content ] end -->
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectAspNETv2/Views/Promotions/Delete.cshtml
@model ProjectAspNETv2.Models.Promotion

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPageDashboard2.cshtml";
}

@*<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Promotion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pourcentage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pourcentage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Validite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Validite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date_Creation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date_Creation)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>*@







<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Promotions</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->
<div class="main-body">
    <div class="page-wrapper">
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header">
                        <h5>
                            Are you sure you want to delete this?
                        </h5>
                    </div>
                    <div class="card-block pb-2 table-border-style">
                        <div class="mb-2">
                            <div class="row">
                                <div class="col-12 col-sm-6 mb-3">
                                    <h5 class="mb-2">
                                        @Html.DisplayNameFor(model => model.Name)
                                    </h5>
                                    <div>
                                        @Html.DisplayFor(model => model.Name)
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 mb-3">
                                    <h5 class="mb-2">
                                        @Html.DisplayNameFor(model => model.Pourcentage)
                                    </h5>
                                    <div>
                                        @Html.DisplayFor(model => model.Pourcentage)
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 mb-3">
                                    <h5 class="mb-2">
                                        @Html.DisplayNameFor(model => model.Date_Creation)
                                    </h5>
                                    <div>
                                        @Html.DisplayFor(model => model.Date_Creation)
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 mb-3">
                                    <h5 class="mb-2">
                                        @Html.DisplayNameFor(model => model.Date_Validite)
                                    </h5>
                                    <div>
                                        @Html.DisplayFor(model => model.Date_Validite)
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-5" style="justify-content : end;">
                            <div style="width : fit-content;">
                                <div style="display:inline-block;">
                                    @using (Html.BeginForm())
                                    {
                                        @Html.AntiForgeryToken()
                                        <button class="btn btn-danger" type="submit">
                                            Delete
                                        </button>
                                    }

                                </div>
                                <div style="display:inline-block;">
                                    <button class="btn btn-secondary" type="button">
                                        <a href="@Url.Action("index" , "Promotions" )" style="display: inline-block; color : #fff ; text-decoration : none;">Liste</a>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>

    </div>

ProjectAspNETv2/Views/Promotions/Details.cshtml
@model ProjectAspNETv2.Models.Promotion

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPageDashboard2.cshtml";
}







<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Promotions</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->
<div class="main-body">
    <div class="page-wrapper">
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Details de Promotion</h5>
                    </div>
                    <div class="card-block pb-2 table-border-style">
                        <div class="mb-2">
                            <div class="row">
                                <div class="col-12 col-sm-6 mb-3">
                                    <h5 class="mb-2">
                                        @Html.DisplayNameFor(model => model.Name)
                                    </h5>
                                    <div>
                                        @Html.DisplayFor(model => model.Name)
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 mb-3">
                                    <h5 class="mb-2">
                                        @Html.DisplayNameFor(model => model.Pourcentage)
                                    </h5>
                                    <div>
                                        @Html.DisplayFor(model => model.Pourcentage)
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 mb-3">
                                    <h5 class="mb-2">
                                        @Html.DisplayNameFor(model => model.Date_Creation)
                                    </h5>
                                    <div>
                                        @Html.DisplayFor(model => model.Date_Creation)
                                    </div>
                                </div>
                                <div class="col-12 col-sm-6 mb-3">
                                    <h5 class="mb-2">
                                        @Html.DisplayNameFor(model => model.Date_Validite)
                                    </h5>
                                    <div>
                                        @Html.DisplayFor(model => model.Date_Validite)
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-5" style="justify-content : end;">
                            <div style="width : fit-content;">
                                <div style="display:inline-block;">
                                    <button class="btn btn-primary" type="button">
                                        <a href="@Url.Action("Index" , "Promotions" )" style="display: inline-block; color : #fff ; text-decoration : none;">Liste</a>

                                    </button>
                                </div>
                                <div style="display:inline-block;">
                                    <button class="btn btn-secondary" type="button">
                                        <a href="@Url.Action("Edit" , "Promotions" , new { id = Model.Id } ) " style="display: inline-block; color : #fff ; text-decoration : none;">Modifier</a>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- [ Main Content ] end -->
            </div>
        </div>

ProjectAspNETv2/Views/Promotions/Edit.cshtml
@model ProjectAspNETv2.Models.Promotion

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPageDashboard2.cshtml";
}











<!-- [ breadcrumb ] start -->
<div class="page-header">
    <div class="page-block">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="page-header-title">
                </div>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html"><i class="feather icon-home"></i></a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Dashboard</a></li>
                    <li class="breadcrumb-item"><a href="javascript:">Promotion</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- [ breadcrumb ] end -->
<div class="main-body">
    <div class="page-wrapper">
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Nouveau produit</h5>
                    </div>
                    <div class="card-block table-border-style">

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                @Html.HiddenFor(model => model.Id)
                                @Html.HiddenFor(model => model.Date_Creation)



                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        <div class="form-group">

                                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Pourcentage, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Pourcentage, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Pourcentage, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Date_Validite, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.Date_Validite, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Date_Validite, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                

                                

                                

                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <input type="submit" value="Edit" class="btn btn-default" />
                                    </div>
                                </div>
                            </div>
                        }

                        <div class="row mt-5" style="justify-content : end;">
                            <div style="width : fit-content;">
                                <div style="display:inline-block;">
                                    <button class="btn btn-primary" type="button">
                                        <a href="@Url.Action("Index" , "Promotions" )" style="display: inline-block; color : #fff ; text-decoration : none;">Liste</a>

                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ Main Content ] end -->
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectAspNETv2/Views/Promotions/Index.cshtml
@model IEnumerable<ProjectAspNETv2.Models.Promotion>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPageDashboard2.cshtml";
}







<!-- [ breadcrumb ] end -->
<div class="main-body">
    <div class="page-wrapper">
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Liste des promotions</h5>
                    </div>
                    <div class="px-3">
                        <div class="input-group mb-3">
                            <input type="text" class="form-control" placeholder="Nom de promotion" aria-label="Recipient's username" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">Trouver</button>
                            </div>
                            <div class="input-group-append">
                                <button class="btn btn-secondary" type="button">
                                    <a href="@Url.Action("Create" , "Promotions")" style="display: inline-block; color : #fff ; text-decoration : none;">Ajouter</a>
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="card-block table-border-style">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Name)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Pourcentage)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Date_Creation)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Date_Validite)
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Pourcentage)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Date_Creation)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Date_Validite)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- [ Main Content ] end -->
    </div>
</div>